- name: Generic pullbook
  hosts: localhost
  vars_files:
    - /root/ansible-pull.vars
  tasks:
    - name: Ensure private group for local admin user exists
      ansible.builtin.group:
        name: "{{ username }}"
        gid: "{{ gid | default(omit) }}"
      when: username is defined
    - name: Ensure local admin user is configured
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "{{ gecos | default(omit) }}"
        uid: "{{ uid | default(omit) }}"
        group: "{{ username }}"
        shell: /bin/bash
        password: "{{ password  | password_hash('sha512') | default(omit) }}"
        update_password: on_create
      when: username is defined
    - name: Ensure local user can sudo
      ansible.builtin.copy:
        dest: /etc/sudoers.d/{{ username }}
        content: "{{ username }} ALL=(ALL:ALL) ALL"
        owner: root
        group: root
        mode: '0440'
    - name: Ensure local admin user has an SSH config directory
      ansible.builtin.file:
        path: /home/{{ username }}/.ssh
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
      when:
        - username is defined
        - key is defined
    - name: Ensure local admin user's SSH key is authorized
      ansible.builtin.lineinfile:
        path: /home/{{ username }}/.ssh/authorized_keys
        line: "{{ key }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
        create: true
      when:
        - username is defined
        - key is defined
